/* Generated by tools/webflash/gen_tables.py - do not edit by hand.
 *
 * Values parsed from the firmware sources:
 *   App/dcs.c
 *   App/dcs.h
 *   App/frequencies.c
 *   App/frequencies.h
 *   App/misc.c
 *   App/misc.h
 *   App/radio.c
 *   App/radio.h
 *   App/settings.h
 *   App/ui/menu.c
 *   App/cn_font.h
 *
 * Re-run the generator after changing any of them; the host test fails
 * when this file is stale.
 */
globalThis.WebFlashTables = {
    "generatedFrom": [
        "App/dcs.c",
        "App/dcs.h",
        "App/frequencies.c",
        "App/frequencies.h",
        "App/misc.c",
        "App/misc.h",
        "App/radio.c",
        "App/radio.h",
        "App/settings.h",
        "App/ui/menu.c",
        "App/cn_font.h"
    ],
    "ctcssOptionsHz10": [
        670,
        693,
        719,
        744,
        770,
        797,
        825,
        854,
        885,
        915,
        948,
        974,
        1000,
        1035,
        1072,
        1109,
        1148,
        1188,
        1230,
        1273,
        1318,
        1365,
        1413,
        1462,
        1514,
        1567,
        1598,
        1622,
        1655,
        1679,
        1713,
        1738,
        1773,
        1799,
        1835,
        1862,
        1899,
        1928,
        1966,
        1995,
        2035,
        2065,
        2107,
        2181,
        2257,
        2291,
        2336,
        2418,
        2503,
        2541
    ],
    "dcsOptions": [
        19,
        21,
        22,
        25,
        26,
        30,
        35,
        39,
        41,
        43,
        44,
        53,
        57,
        58,
        59,
        60,
        76,
        77,
        78,
        82,
        85,
        89,
        90,
        92,
        99,
        101,
        106,
        109,
        110,
        114,
        117,
        122,
        124,
        133,
        138,
        147,
        149,
        150,
        163,
        164,
        165,
        166,
        169,
        170,
        173,
        177,
        179,
        181,
        182,
        185,
        188,
        198,
        201,
        205,
        213,
        217,
        218,
        227,
        230,
        233,
        238,
        244,
        245,
        249,
        265,
        266,
        267,
        275,
        281,
        282,
        293,
        294,
        298,
        300,
        301,
        306,
        308,
        309,
        310,
        323,
        326,
        334,
        339,
        342,
        346,
        358,
        373,
        390,
        394,
        404,
        407,
        409,
        410,
        428,
        434,
        436,
        451,
        458,
        467,
        473,
        474,
        476,
        483,
        492
    ],
    "powerLabels": [
        "USER",
        "LOW 1",
        "LOW 2",
        "LOW 3",
        "LOW 4",
        "LOW 5",
        "MID",
        "HIGH"
    ],
    "modulation": {
        "MODULATION_FM": 0,
        "MODULATION_AM": 1,
        "MODULATION_USB": 2,
        "MODULATION_UKNOWN": 3
    },
    "modulationLabels": {
        "MODULATION_FM": "FM",
        "MODULATION_AM": "AM",
        "MODULATION_USB": "USB"
    },
    "modulationCount": 3,
    "codeType": {
        "CODE_TYPE_OFF": 0,
        "CODE_TYPE_CONTINUOUS_TONE": 1,
        "CODE_TYPE_DIGITAL": 2,
        "CODE_TYPE_REVERSE_DIGITAL": 3
    },
    "offsetDirection": {
        "TX_OFFSET_FREQUENCY_DIRECTION_OFF": 0,
        "TX_OFFSET_FREQUENCY_DIRECTION_ADD": 1,
        "TX_OFFSET_FREQUENCY_DIRECTION_SUB": 2
    },
    "steps": [
        {
            "name": "STEP_2_5kHz",
            "hz100": 250
        },
        {
            "name": "STEP_5kHz",
            "hz100": 500
        },
        {
            "name": "STEP_6_25kHz",
            "hz100": 625
        },
        {
            "name": "STEP_10kHz",
            "hz100": 1000
        },
        {
            "name": "STEP_12_5kHz",
            "hz100": 1250
        },
        {
            "name": "STEP_25kHz",
            "hz100": 2500
        },
        {
            "name": "STEP_8_33kHz",
            "hz100": 833
        },
        {
            "name": "STEP_0_01kHz",
            "hz100": 1
        },
        {
            "name": "STEP_0_05kHz",
            "hz100": 5
        },
        {
            "name": "STEP_0_1kHz",
            "hz100": 10
        },
        {
            "name": "STEP_0_25kHz",
            "hz100": 25
        },
        {
            "name": "STEP_0_5kHz",
            "hz100": 50
        },
        {
            "name": "STEP_1kHz",
            "hz100": 100
        },
        {
            "name": "STEP_1_25kHz",
            "hz100": 125
        },
        {
            "name": "STEP_9kHz",
            "hz100": 900
        },
        {
            "name": "STEP_15kHz",
            "hz100": 1500
        },
        {
            "name": "STEP_20kHz",
            "hz100": 2000
        },
        {
            "name": "STEP_30kHz",
            "hz100": 3000
        },
        {
            "name": "STEP_50kHz",
            "hz100": 5000
        },
        {
            "name": "STEP_100kHz",
            "hz100": 10000
        },
        {
            "name": "STEP_125kHz",
            "hz100": 12500
        },
        {
            "name": "STEP_200kHz",
            "hz100": 20000
        },
        {
            "name": "STEP_250kHz",
            "hz100": 25000
        },
        {
            "name": "STEP_500kHz",
            "hz100": 50000
        }
    ],
    "bandwidth": {
        "BANDWIDTH_WIDE": 0,
        "BANDWIDTH_NARROW": 1
    },
    "bandLowerHz10": [
        1800000,
        10800000,
        13700000,
        17400000,
        35000000,
        40000000,
        47000000
    ],
    "bandLabels": [
        "50MHz",
        "108MHz",
        "137MHz",
        "174MHz",
        "350MHz",
        "400MHz",
        "470MHz"
    ],
    "pttIdLabels": [
        "OFF",
        "BEGIN OF TX",
        "END OF TX",
        "BOTH",
        "APOLLO"
    ],
    "mrChannelsMax": 1024,
    "scanLists": 24,
    "recordSize": 16,
    "namesBase": 16384,
    "namesSlotSize": 16,
    "nameMaxBytes": 15,
    "attrsBase": 32768,
    "attrsSize": 2,
    "eepromReadMax": 128,
    "eepromOffsetMax": 65536,
    "font": {
        "base": 1757184,
        "totalSize": 205367,
        "charCount": 6766,
        "bitmapSize": 162384,
        "indexSize": 27064,
        "pyOffset": 189448,
        "pyCount": 402,
        "pyTotalSize": 15918,
        "version": 2,
        "versionOffset": 205366,
        "chunkSize": 128
    },
    "cmd": {
        "devInfo": 1300,
        "devInfoRsp": 1301,
        "readEeprom": 1307,
        "readEepromRsp": 1308,
        "writeEeprom": 1309,
        "writeEepromRsp": 1310,
        "reset": 1501,
        "fontInfo": 1856,
        "fontInfoRsp": 1857,
        "fontWrite": 1858,
        "fontWriteRsp": 1859,
        "fontRead": 1860,
        "fontReadRsp": 1861
    },
    "status": {
        "ok": 0,
        "auth": 1,
        "range": 2,
        "size": 3
    },
    "regions": {
        "kernel": [
            {
                "name": "multiboot state A",
                "base": 1048576,
                "end": 1052672
            },
            {
                "name": "multiboot state B",
                "base": 1052672,
                "end": 1056768
            },
            {
                "name": "overlay apps",
                "base": 1056768,
                "end": 1187840
            },
            {
                "name": "voice index",
                "base": 1359872,
                "end": 1363968
            },
            {
                "name": "voice data",
                "base": 1363968,
                "end": null
            },
            {
                "name": "RX/TX log",
                "base": 1966080,
                "end": null
            }
        ],
        "overlayApps": {
            "base": 1056768,
            "end": 1187840
        },
        "voiceIndexBase": 1359872,
        "voiceDataBase": 1363968,
        "rxtxLogBase": 1966080,
        "flashSize": 2097152
    }
};
