#!/usr/bin/env python3
"""Run the host-side tests for the Chinese channel-name support.

These build the real firmware sources (App/cn_font.c, App/ui/helper.c,
App/font.c and the extracted channel-name code) for the *host*, against a
stubbed serial port and external flash, so the font layout, the upload protocol
and the name storage can be checked without a radio. Nothing here is part of the
firmware build.

    python tools/cn_font/host_tests/run_host_tests.py [--blob PATH]

Needs a host C compiler (gcc or cc) on PATH. The font blob defaults to the
reference one in Dondji/docs/font/cn_font.bin.
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))

INCLUDES = (
    "App",
    "App/external",
    "App/usb",
    os.path.join("Drivers", "PY32F071_HAL_Driver", "Inc"),
    os.path.join("Drivers", "CMSIS", "Device", "PY32F071", "Include"),
    os.path.join("Drivers", "CMSIS", "Include"),
    os.path.join("Drivers", "CMSIS", "Core", "Include"),
)

DEFINES = ("PY32F071xB", "ENABLE_CHINESE", "PRINTF_INCLUDE_CONFIG_H")

# Tests: (name, main source, extra firmware sources, needs the font blob)
TESTS = (
    ("font + drawing", "host_font.c",
     (r"App\cn_font.c", r"App\ui\helper.c", r"App\font.c",
      r"App\external\printf\printf.c"), True),
    ("name storage", "host_names.c", (r"App\cn_font.c",), True),
    ("name editor cursor", "host_editor.c", (r"App\cn_font.c",), True),
    ("upload protocol", "host_protocol.py", (), True),
)


def find_compiler():
    for candidate in ("gcc", "cc", "clang"):
        found = shutil.which(candidate)
        if found:
            return found
    raise SystemExit("no host C compiler found (tried gcc, cc, clang)")


def extract(workdir):
    """Pull the channel-name and editor functions out of the firmware sources so
    the tests run the real code rather than a copy."""
    targets = []

    def grab(source, output, signatures, guard=None):
        with open(os.path.join(REPO, source), encoding="utf-8") as handle:
            text = handle.read()

        chunks = []

        for signature in signatures:
            if signature not in text:
                raise SystemExit("%s: not found: %s" % (source, signature))
            start = text.index(signature)
            open_brace = text.index("{", start)
            depth = 0
            i = open_brace
            while i < len(text):
                if text[i] == "{":
                    depth += 1
                elif text[i] == "}":
                    depth -= 1
                    if depth == 0:
                        break
                i += 1
            chunks.append(text[start:i + 1])

        path = os.path.join(workdir, output)
        with open(path, "w", encoding="utf-8") as handle:
            handle.write("/* generated by run_host_tests.py - do not edit */\n")
            if guard:
                handle.write("#ifdef %s\n" % guard)
            handle.write("\n\n".join(chunks))
            if guard:
                handle.write("\n#endif\n")
            handle.write("\n")
        targets.append(path)
        print("  extracted %d chunk(s) from %s" % (len(chunks), source))

    grab(r"App\settings.c", "extracted_names.h",
         ("void SETTINGS_FetchChannelName(",
          "void SETTINGS_SaveChannelName(",
          "bool SETTINGS_ChannelNameHasCjk("),
         guard="ENABLE_CHINESE")

    grab(r"App\app\menu.c", "extracted_editor.h",
         ("int MENU_MemNameNextSlotIndex(",
          "int MENU_MemNamePrevSlotIndex(",
          "static void MENU_MemNamePutAsciiChar("),
         guard="ENABLE_CHINESE")

    return targets


def build(compiler, workdir, main_source, sources):
    binary = os.path.join(workdir, os.path.splitext(main_source)[0] + ".exe"
                          if os.name == "nt" else os.path.splitext(main_source)[0])

    cmd = [compiler, "-std=gnu11", "-Wall", "-O1"]
    cmd += ["-D%s" % d for d in DEFINES]
    cmd += ["-I", workdir]
    for include in INCLUDES:
        cmd += ["-I", os.path.join(REPO, include)]
    cmd += ["-o", binary, os.path.join(HERE, main_source)]
    cmd += [os.path.join(REPO, src) for src in sources]

    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        print(proc.stdout)
        print(proc.stderr)
        raise SystemExit("compilation failed for %s" % main_source)

    return binary


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--blob", default=os.path.join(REPO, "Dondji", "docs", "font", "cn_font.bin"),
                        help="font blob to test with")
    args = parser.parse_args()

    if not os.path.isfile(args.blob):
        raise SystemExit("font blob not found: %s" % args.blob)

    compiler = find_compiler()
    workdir = tempfile.mkdtemp(prefix="cn_font_host_tests_")
    failures = 0

    try:
        print("compiler: %s" % compiler)
        print("blob: %s (%d bytes)" % (args.blob, os.path.getsize(args.blob)))
        extract(workdir)

        for name, main_source, sources, needs_blob in TESTS:
            print("\n== %s ==" % name)

            if main_source.endswith(".py"):
                cmd = [sys.executable, os.path.join(HERE, main_source),
                       "--blob", args.blob, "--tools", os.path.join(REPO, "tools", "cn_font")]
                proc = subprocess.run(cmd, text=True)
            else:
                binary = build(compiler, workdir, main_source, sources)
                cmd = [binary] + ([args.blob] if needs_blob else [])
                proc = subprocess.run(cmd, text=True)

            if proc.returncode != 0:
                failures += 1

        print("\n%s" % ("all host tests passed" if failures == 0
                        else "%d test(s) failed" % failures))
        return 1 if failures else 0
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
